services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:app:cached
    command: ["sleep", "infinity"]
    networks: [net]
    ports:
      - "18443:18443"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/app:cached
    command: ["sleep", "infinity"]
    networks: [net]

networks:
  net:
    driver: bridge
